name: Build and Release (Beta)

on:
  release:
    types: [published]

env:
  APP_NAME: webdav-drive
  OUTPUT_EXE: webdav-drive.exe

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install Inno Setup
        run: |
          choco install innosetup -y

      - name: Build Go executable
        run: |
          go build -ldflags="-H windowsgui -s -w -X main.version=${{ github.ref_name }}" -o bin/${{ env.OUTPUT_EXE }} ./src

      - name: Create SHA256 checksum
        run: |
          cd bin
          certutil -hashfile ${{ env.OUTPUT_EXE }} SHA256 | findstr /r "[0-9a-fA-F]" > ${{ env.OUTPUT_EXE }}.sha256

      - name: Build Inno Setup installer
        run: |
          iscc "installer\webdav-drive.iss"
        shell: cmd

      - name: Upload portable executable
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./bin/${{ env.OUTPUT_EXE }}
          asset_name: webdav-drive.exe
          asset_content_type: application/octet-stream

      - name: Upload SHA256 checksum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./bin/${{ env.OUTPUT_EXE }}.sha256
          asset_name: webdav-drive.exe.sha256
          asset_content_type: text/plain

      - name: Upload installer
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./webdav-drive-setup.exe
          asset_name: webdav-drive-setup.exe
          asset_content_type: application/octet-stream